version: '3'
services:
  webserver_aps:
    container_name: aps_new_nginx
    image: nginx:stable-alpine
    restart: always
    tty: true
    ports:
    - 8484:80
    volumes:
    - ./:/var/www/html
    - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network-aps

  app_aps:
    image: aps_new_app/php
    container_name: aps_new_app
    restart: unless-stopped
    tty: true
    build: 
      context: .
      dockerfile: ./docker/php/Dockerfile
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/custome.ini:/usr/local/etc/php/conf.d/custome.ini
    networks:
      - app-network-aps

#Docker Networks
networks:
  app-network-aps:
    driver: bridge